name: super_res_env
channels:
  - conda-forge
  - pytorch
  - defaults
dependencies:
  - python=3.12
  - pytorch=2.4.0
  - torchvision=0.19.0
  - torchaudio=2.4.0
  - cudatoolkit=11.8  
  - numpy=1.26.4
  - pillow  
  - rasterio  # For geospatial data handling
  - matplotlib=3.9.2 
  - pandas=2.2.2  
  - pip
  - pip:
    - torch-optimizer  # For Adam optimizer 
    - torchmetrics  # For lr_scheduler 
    - ipykernel
    - jupyterlab 
    - tqdm  
    - ipywidgets
    - tacoreader  
    - super-image